# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bb850762ded777de3d2b7e1aa6c88b5cb1404417d1197a833afd39636e2107b5106ad1297ad553a3c9a1fad59bbae5baea89c71d0f7df84d7864667b6658f00

test:
  secret_key_base: 1b2cf1bd513d1e70588353a9b01009f03d22260da07f82a9217b30d40fd73e33ff0ffe05668029c504b0e83af6efeffaf0c4cf308037da40881183a867ade272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
